// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Lf0leqGJyyIcrn-NHAKjKxOetTguooA',
    appId: '1:926939474937:web:4c1000f09d8cc56bceab28',
    messagingSenderId: '926939474937',
    projectId: 'plannova-4b209',
    authDomain: 'plannova-4b209.firebaseapp.com',
    storageBucket: 'plannova-4b209.firebasestorage.app',
    measurementId: 'G-HNGN4LHPTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5i_scHa4log258qg_BTGnJ8w5QHtZC0',
    appId: '1:926939474937:android:d001f5393675ddf1ceab28',
    messagingSenderId: '926939474937',
    projectId: 'plannova-4b209',
    storageBucket: 'plannova-4b209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXp0-0eAsSTwtw8gh87Lpgw3NW20clGxg',
    appId: '1:926939474937:ios:a585e1c0ab674bb6ceab28',
    messagingSenderId: '926939474937',
    projectId: 'plannova-4b209',
    storageBucket: 'plannova-4b209.firebasestorage.app',
    iosBundleId: 'com.example.plannova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXp0-0eAsSTwtw8gh87Lpgw3NW20clGxg',
    appId: '1:926939474937:ios:a585e1c0ab674bb6ceab28',
    messagingSenderId: '926939474937',
    projectId: 'plannova-4b209',
    storageBucket: 'plannova-4b209.firebasestorage.app',
    iosBundleId: 'com.example.plannova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Lf0leqGJyyIcrn-NHAKjKxOetTguooA',
    appId: '1:926939474937:web:d34f48f8a3ca6cf1ceab28',
    messagingSenderId: '926939474937',
    projectId: 'plannova-4b209',
    authDomain: 'plannova-4b209.firebaseapp.com',
    storageBucket: 'plannova-4b209.firebasestorage.app',
    measurementId: 'G-K2H9KDLH6X',
  );
}
